#!/bin/bash
DIR="$(cd "$(dirname "$0")" && pwd)"
coffee="$DIR/../node_modules/.bin/coffee"
source_dir="$DIR/../source"
build_dir="$DIR/../build"
spec_dir="$DIR/../spec"
bin_dir="$DIR/../bin"
docs_dir="$DIR/../docs"
npm_dir="$DIR/.."


clean() {
  find build -name *.js -print0 | xargs -0 rm -f
  find build -name *.map -print0 | xargs -0 rm -f
  find spec -name *.spec.coffee -print0 | xargs -0 rm -f
}

build-source() {
  $coffee -cmb -o $build_dir $source_dir
}

build-readme() {
  cat $docs_dir/JasmineJavaScript.coffee.md > $npm_dir/README.md
  echo -e "\n--------------------------------------------------------------------------------\n" >> $npm_dir/README.md
  cat $npm_dir/LICENSE.md >> $npm_dir/README.md
}

build-specs() {
  NODE_PATH=$NODE_PATH:$npm_dir $npm_dir/node_modules/.bin/boco-markdown-driven -c $npm_dir/markdown-driven.json "docs/**/*.coffee.md"
}

build() {
  build-source
  build-readme
  build-specs
}

argv=("$*")
for arg in $argv; do eval ${arg}; done
